#!/usr/bin/env node
/**
 * The three plugin operations that are LOGIC rather than shell, and so are worth a real file:
 *
 *   link     symlink plugins/ into the site's node_modules. Platform-specific on purpose — Node
 *            handles junctions on Windows, which `ln -s` does not.
 *   audit    the structural rules (phantom scripts, unbuilt sandbox bundles, emdash drift,
 *            empty allowedHosts). Each rule encodes a bug found by hand.
 *   catalog  fetch the registry and write docs/plugin-catalog/.
 *
 * Everything else that used to be a subcommand here — install, install-all, build, bundle,
 * validate, typecheck, init, dev — was a loop over `plugins/` running `pnpm`, and is a nushell
 * task in mise.toml now. `plugin:_sweep` covers the four that share one rule.
 */
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname } from "node:path";

import { env, run } from "./lib/exec.mjs";

const ROOT = env("ROOT");
const PLUGINS_DIR = env("PLUGINS_DIR");
const SITE_DIR = env("SITE_DIR");
const sub = process.argv[2];
const name = process.argv[3];

const pluginDirs = () =>
	readdirSync(PLUGINS_DIR, { withFileTypes: true })
		.filter(
			(entry) => entry.isDirectory() && existsSync(`${PLUGINS_DIR}/${entry.name}/package.json`),
		)
		.map((entry) => entry.name);

function readJson(path) {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return null;
	}
}

/**
 * Fetch every package from the EmDash registry and write docs/plugin-catalog/.
 *
 * The registry is the source of truth for published plugins — a GitHub scrape (what this
 * used to do) goes stale and misses anything not hosted on GitHub.
 */
async function catalog(dry) {
	const base = process.env.CATALOG_REGISTRY_URL ?? "https://registry.emdashcms.com";
	const packages = [];
	for (let cursor = ""; ;) {
		const url = new URL(`${base}/xrpc/com.emdashcms.experimental.aggregator.searchPackages`);
		url.searchParams.set("limit", "100");
		if (cursor) url.searchParams.set("cursor", cursor);
		const res = await fetch(url);
		if (!res.ok) throw new Error(`${res.status} from ${url.host}`);
		const body = await res.json();
		packages.push(...(body.packages ?? []));
		cursor = body.cursor ?? "";
		if (!cursor) break;
	}
	packages.sort((a, b) => (a.profile?.name ?? a.slug).localeCompare(b.profile?.name ?? b.slug));

	const rows = packages.map((pkg) => {
		const authors = (pkg.profile?.authors ?? [])
			.map((author) => author.name)
			.filter(Boolean)
			.join(", ");
		const description = (pkg.profile?.description ?? "").replace(/\s+/g, " ").trim();
		return `| ${pkg.profile?.name ?? pkg.slug} | \`${pkg.slug}\` | ${authors || "—"} | ${pkg.profile?.license ?? "—"} | ${description.slice(0, 130)} |`;
	});

	const markdown = `# Plugin catalog

Live packages published to the EmDash **registry** — generated by \`mise run plugin:catalog\`.

- Source: \`${base}\`
- Generated: ${new Date().toISOString().slice(0, 10)}
- Packages: ${packages.length}

| Name | Slug | Author | License | Description |
|------|------|--------|---------|-------------|
${rows.join("\n")}
`;

	if (dry) {
		console.log(markdown);
		return;
	}
	// Keep only stable, useful fields. The raw records carry `cid`, `labels` and
	// `indexedAt`, which change on every publish — committing those makes the diff noise.
	const slim = packages.map((pkg) => ({
		slug: pkg.slug,
		did: pkg.did,
		handle: pkg.handle ?? null,
		name: pkg.profile?.name ?? pkg.slug,
		description: pkg.profile?.description ?? "",
		authors: (pkg.profile?.authors ?? []).map((author) => author.name).filter(Boolean),
		license: pkg.profile?.license ?? null,
		keywords: pkg.profile?.keywords ?? [],
		latestVersion: pkg.latestVersion ?? null,
	}));

	mkdirSync(`${ROOT}/docs/plugin-catalog`, { recursive: true });
	writeFileSync(`${ROOT}/docs/plugin-catalog/README.md`, markdown);
	writeFileSync(
		`${ROOT}/docs/plugin-catalog/packages.json`,
		`${JSON.stringify(slim, null, "\t")}\n`,
	);
	console.log(`  ✓ ${packages.length} packages → docs/plugin-catalog/`);
}

/**
 * Structural checks across every plugin in `plugins/`.
 *
 * Every rule here encodes a bug that was found by hand, and each one presented as "the
 * feature is broken" when the real fault was a file describing a setup that did not exist:
 *
 *   1. A script the toolchain can never run. The native plugin declared `validate`, `build`,
 *      `bundle` and `test` pointing at the sandboxed CLI while having no manifest and no
 *      tests. Unrunnable for months; it only surfaced when a sweep tried to run one.
 *   2. A sandboxed plugin whose `./sandbox` entry has not been built. The descriptor names a
 *      built bundle as its entrypoint, so linking without building leaves the site importing
 *      a file that is not there.
 *   3. A plugin pinned to a different `emdash` than the site runs. The scaffold asked for
 *      0.x and installed 0.42.0 while the site ran 1.1.0 — so its passing test was evidence
 *      about a different CMS.
 *   4. `network:request` with nothing to allow. The bundle-time check rejects it, so failing
 *      here just fails earlier, with a better message.
 *
 * The manifest is parsed with regexes rather than a JSONC parser on purpose: this is a
 * lint, and `emdash-plugin validate` remains the authority on whether a manifest is valid.
 */
function audit() {
	const failures = [];

	const siteEmdash = readJson(`${SITE_DIR}/node_modules/emdash/package.json`)?.version ?? null;

	for (const dir of pluginDirs()) {
		const abs = `${PLUGINS_DIR}/${dir}`;
		const manifest = readJson(`${abs}/package.json`);
		if (!manifest) continue;

		const label = manifest.name ?? dir;
		const hasPluginManifest = existsSync(`${abs}/emdash-plugin.jsonc`);

		// 1. a script the toolchain cannot run.
		for (const [scriptName, command] of Object.entries(manifest.scripts ?? {})) {
			if (/\bemdash-plugin\b/.test(command) && !hasPluginManifest) {
				failures.push(
					`${label}: script "${scriptName}" runs emdash-plugin but the plugin has no emdash-plugin.jsonc — it can never succeed`,
				);
			}
		}

		// 2. the sandbox bundle has not been built.
		const entry = manifest.exports?.["./sandbox"];
		const relative = typeof entry === "string" ? entry : (entry?.import ?? entry?.default);
		if (hasPluginManifest && typeof relative === "string" && !existsSync(`${abs}/${relative}`)) {
			failures.push(
				`${label}: exports "./sandbox" → ${relative}, which does not exist — run \`mise run plugin:build\``,
			);
		}

		// 3. emdash drift from the site.
		const pinned = readJson(`${abs}/node_modules/emdash/package.json`)?.version ?? null;
		if (siteEmdash && pinned && pinned !== siteEmdash) {
			failures.push(
				`${label}: has emdash ${pinned} installed, but the site runs ${siteEmdash} — a green test here says nothing about the site`,
			);
		}

		// 4. network access declared with nothing to allow.
		if (hasPluginManifest) {
			const raw = readFileSync(`${abs}/emdash-plugin.jsonc`, "utf8");
			const list = (key) => new RegExp(`"${key}"\\s*:\\s*\\[([^\\]]*)\\]`).exec(raw)?.[1] ?? "";
			const capabilities = list("capabilities");
			if (
				capabilities.includes("network:request") &&
				!capabilities.includes("network:request:unrestricted")
			) {
				if (!list("allowedHosts").trim()) {
					failures.push(
						`${label}: declares network:request but allowedHosts is empty — the bundle-time check will reject it`,
					);
				}
			}
		}
	}

	if (failures.length) {
		console.error(`plugin:audit found ${failures.length} problem(s):`);
		for (const failure of failures) console.error(`  ✗ ${failure}`);
		process.exit(1);
	}
	console.log(`  ✓ ${pluginDirs().length} plugins consistent`);
}

switch (sub) {
		case "link":
		// Plugins live in plugins/ but the site resolves them from its own node_modules;
		// symlinking keeps edits live.
		mkdirSync(`${SITE_DIR}/node_modules`, { recursive: true });
		for (const dir of pluginDirs()) {
			const pkg = JSON.parse(readFileSync(`${PLUGINS_DIR}/${dir}/package.json`, "utf8")).name;
			const target = `${SITE_DIR}/node_modules/${pkg}`;
			mkdirSync(dirname(target), { recursive: true });
			rmSync(target, { recursive: true, force: true });
			symlinkSync(`${PLUGINS_DIR}/${dir}`, target);
			console.log(`  ✓ linked ${pkg}`);
		}
		break;

		case "audit":
		audit();
		break;

	case "catalog":
		await catalog(false);
		break;

		default:
		console.error(`plugins: unknown subcommand "${sub}"`);
		process.exit(1);
}
