#!/usr/bin/env node
/**
 *   mise run plugin:install -- <name>          (one plugin)
 *   mise run plugin:install-all | plugin:link (all plugins)
 *   mise run plugin:validate|bundle|publish|login -- <name>
 *   mise run plugin:catalog | :catalog:dry | :catalog:full
 *
 * Singular = one plugin (takes a name); plural = all plugins.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { env, run } from "./lib/exec.mjs";

const ROOT = env("ROOT");
const PLUGINS_DIR = env("PLUGINS_DIR");
const SITE_DIR = env("SITE_DIR");
const sub = process.argv[2];
const name = process.argv[3];

const pluginDirs = () =>
	readdirSync(PLUGINS_DIR, { withFileTypes: true })
		.filter((entry) => entry.isDirectory() && existsSync(`${PLUGINS_DIR}/${entry.name}/package.json`))
		.map((entry) => entry.name);

function requireName() {
	if (!name) {
		console.error(`plugin:${sub} needs a plugin name — e.g: mise run plugin:${sub} -- plat-trunk`);
		process.exit(1);
	}
}

/**
 * Fetch every package from the EmDash registry and write docs/plugin-catalog/.
 *
 * The registry is the source of truth for published plugins — a GitHub scrape (what this
 * used to do) goes stale and misses anything not hosted on GitHub.
 */
async function catalog(dry) {
	const base = process.env.CATALOG_REGISTRY_URL ?? "https://registry.emdashcms.com";
	const packages = [];
	for (let cursor = ""; ; ) {
		const url = new URL(`${base}/xrpc/com.emdashcms.experimental.aggregator.searchPackages`);
		url.searchParams.set("limit", "100");
		if (cursor) url.searchParams.set("cursor", cursor);
		const res = await fetch(url);
		if (!res.ok) throw new Error(`${res.status} from ${url.host}`);
		const body = await res.json();
		packages.push(...(body.packages ?? []));
		cursor = body.cursor ?? "";
		if (!cursor) break;
	}
	packages.sort((a, b) => (a.profile?.name ?? a.slug).localeCompare(b.profile?.name ?? b.slug));

	const rows = packages.map((pkg) => {
		const authors = (pkg.profile?.authors ?? []).map((author) => author.name).filter(Boolean).join(", ");
		const description = (pkg.profile?.description ?? "").replace(/\s+/g, " ").trim();
		return `| ${pkg.profile?.name ?? pkg.slug} | \`${pkg.slug}\` | ${authors || "—"} | ${pkg.profile?.license ?? "—"} | ${description.slice(0, 130)} |`;
	});

	const markdown = `# Plugin catalog

Live packages published to the EmDash **registry** — generated by \`mise run plugin:catalog\`.

- Source: \`${base}\`
- Generated: ${new Date().toISOString().slice(0, 10)}
- Packages: ${packages.length}

| Name | Slug | Author | License | Description |
|------|------|--------|---------|-------------|
${rows.join("\n")}
`;

	if (dry) {
		console.log(markdown);
		return;
	}
	// Keep only stable, useful fields. The raw records carry `cid`, `labels` and
	// `indexedAt`, which change on every publish — committing those makes the diff noise.
	const slim = packages.map((pkg) => ({
		slug: pkg.slug,
		did: pkg.did,
		handle: pkg.handle ?? null,
		name: pkg.profile?.name ?? pkg.slug,
		description: pkg.profile?.description ?? "",
		authors: (pkg.profile?.authors ?? []).map((author) => author.name).filter(Boolean),
		license: pkg.profile?.license ?? null,
		keywords: pkg.profile?.keywords ?? [],
		latestVersion: pkg.latestVersion ?? null,
	}));

	mkdirSync(`${ROOT}/docs/plugin-catalog`, { recursive: true });
	writeFileSync(`${ROOT}/docs/plugin-catalog/README.md`, markdown);
	writeFileSync(`${ROOT}/docs/plugin-catalog/packages.json`, `${JSON.stringify(slim, null, "\t")}\n`);
	console.log(`  ✓ ${packages.length} packages → docs/plugin-catalog/`);
}

switch (sub) {
	case "install":
		requireName();
		run("pnpm", ["install"], { cwd: `${PLUGINS_DIR}/${name}` });
		break;

	case "install-all":
		for (const dir of pluginDirs()) {
			console.log(`→ pnpm install in ${dir}`);
			run("pnpm", ["install"], { cwd: `${PLUGINS_DIR}/${dir}` });
		}
		break;

	case "link":
		// Plugins live in plugins/ but the site resolves them from its own node_modules;
		// symlinking keeps edits live.
		mkdirSync(`${SITE_DIR}/node_modules`, { recursive: true });
		for (const dir of pluginDirs()) {
			const pkg = JSON.parse(readFileSync(`${PLUGINS_DIR}/${dir}/package.json`, "utf8")).name;
			const target = `${SITE_DIR}/node_modules/${pkg}`;
			mkdirSync(dirname(target), { recursive: true });
			rmSync(target, { recursive: true, force: true });
			symlinkSync(`${PLUGINS_DIR}/${dir}`, target);
			console.log(`  ✓ linked ${pkg}`);
		}
		break;

	case "validate":
	case "bundle":
	case "publish":
	case "login":
		// Deliberately not implemented: these belong to the sandboxed-plugin flow
		// (`@emdash-cms/plugin-cli` / `emdash-plugin`, needs an emdash-plugin.jsonc).
		// plat-trunk is native, distributed as an npm package. See docs/plugin.md.
		console.error(`${sub}: not applicable — sandboxed plugins only (see docs/plugin.md)`);
		process.exit(1);

	case "catalog":
		await catalog(false);
		break;
	case "catalog-dry":
		await catalog(true);
		break;

	default:
		console.error(`plugins: unknown subcommand "${sub}"`);
		process.exit(1);
}
