#!/usr/bin/env node
/**
 * The plugin SWEEPS — the subcommands that iterate `plugins/` and run each plugin's OWN script,
 * so a new plugin joins the flow by declaring the script and nothing here changes. That is why
 * native and sandboxed plugins coexist without a branch on which kind they are.
 *
 *   mise run plugin:install -- <name>           (one plugin)
 *   mise run plugin:install-all | plugin:link   (all plugins)
 *   mise run plugin:build | :bundle | :validate | :typecheck | :audit
 *   mise run plugin:catalog
 *
 * The one-shot commands that only call the official CLI — `login`, `logout`, `whoami`, `profile`,
 * `switch`, `info`, `release`, `update-package`, `search` — are plain tasks in mise.toml now.
 * They were advertised here as subcommands, but this file never had a `case` for any of them, so
 * every one of them fell through to `default` and died with "unknown subcommand". A relay that
 * does not relay is worse than no relay.
 */
import {
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	symlinkSync,
	writeFileSync,
} from "node:fs";
import { dirname } from "node:path";

import { env, run } from "./lib/exec.mjs";

const ROOT = env("ROOT");
const PLUGINS_DIR = env("PLUGINS_DIR");
const SITE_DIR = env("SITE_DIR");
const sub = process.argv[2];
const name = process.argv[3];

const pluginDirs = () =>
	readdirSync(PLUGINS_DIR, { withFileTypes: true })
		.filter(
			(entry) => entry.isDirectory() && existsSync(`${PLUGINS_DIR}/${entry.name}/package.json`),
		)
		.map((entry) => entry.name);

function readJson(path) {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch {
		return null;
	}
}

function requireName() {
	if (!name) {
		console.error(`plugin:${sub} needs a plugin name — e.g: mise run plugin:${sub} -- plat-trunk`);
		process.exit(1);
	}
}

/**
 * Fetch every package from the EmDash registry and write docs/plugin-catalog/.
 *
 * The registry is the source of truth for published plugins — a GitHub scrape (what this
 * used to do) goes stale and misses anything not hosted on GitHub.
 */
/**
 * The `emdash-plugin` binary, from `@emdash-cms/plugin-cli`.
 *
 * Taken from the PATH rather than borrowed from a plugin's node_modules: the CLI is scheduled as
 * a mise tool in its own right, so there is no longer a "which plugin happens to have it
 * installed" question.
 */
const PLUGIN_CLI = "emdash-plugin";

async function catalog(dry) {
	const base = process.env.CATALOG_REGISTRY_URL ?? "https://registry.emdashcms.com";
	const packages = [];
	for (let cursor = ""; ;) {
		const url = new URL(`${base}/xrpc/com.emdashcms.experimental.aggregator.searchPackages`);
		url.searchParams.set("limit", "100");
		if (cursor) url.searchParams.set("cursor", cursor);
		const res = await fetch(url);
		if (!res.ok) throw new Error(`${res.status} from ${url.host}`);
		const body = await res.json();
		packages.push(...(body.packages ?? []));
		cursor = body.cursor ?? "";
		if (!cursor) break;
	}
	packages.sort((a, b) => (a.profile?.name ?? a.slug).localeCompare(b.profile?.name ?? b.slug));

	const rows = packages.map((pkg) => {
		const authors = (pkg.profile?.authors ?? [])
			.map((author) => author.name)
			.filter(Boolean)
			.join(", ");
		const description = (pkg.profile?.description ?? "").replace(/\s+/g, " ").trim();
		return `| ${pkg.profile?.name ?? pkg.slug} | \`${pkg.slug}\` | ${authors || "—"} | ${pkg.profile?.license ?? "—"} | ${description.slice(0, 130)} |`;
	});

	const markdown = `# Plugin catalog

Live packages published to the EmDash **registry** — generated by \`mise run plugin:catalog\`.

- Source: \`${base}\`
- Generated: ${new Date().toISOString().slice(0, 10)}
- Packages: ${packages.length}

| Name | Slug | Author | License | Description |
|------|------|--------|---------|-------------|
${rows.join("\n")}
`;

	if (dry) {
		console.log(markdown);
		return;
	}
	// Keep only stable, useful fields. The raw records carry `cid`, `labels` and
	// `indexedAt`, which change on every publish — committing those makes the diff noise.
	const slim = packages.map((pkg) => ({
		slug: pkg.slug,
		did: pkg.did,
		handle: pkg.handle ?? null,
		name: pkg.profile?.name ?? pkg.slug,
		description: pkg.profile?.description ?? "",
		authors: (pkg.profile?.authors ?? []).map((author) => author.name).filter(Boolean),
		license: pkg.profile?.license ?? null,
		keywords: pkg.profile?.keywords ?? [],
		latestVersion: pkg.latestVersion ?? null,
	}));

	mkdirSync(`${ROOT}/docs/plugin-catalog`, { recursive: true });
	writeFileSync(`${ROOT}/docs/plugin-catalog/README.md`, markdown);
	writeFileSync(
		`${ROOT}/docs/plugin-catalog/packages.json`,
		`${JSON.stringify(slim, null, "\t")}\n`,
	);
	console.log(`  ✓ ${packages.length} packages → docs/plugin-catalog/`);
}

/**
 * Structural checks across every plugin in `plugins/`.
 *
 * Every rule here encodes a bug that was found by hand, and each one presented as "the
 * feature is broken" when the real fault was a file describing a setup that did not exist:
 *
 *   1. A script the toolchain can never run. The native plugin declared `validate`, `build`,
 *      `bundle` and `test` pointing at the sandboxed CLI while having no manifest and no
 *      tests. Unrunnable for months; it only surfaced when a sweep tried to run one.
 *   2. A sandboxed plugin whose `./sandbox` entry has not been built. The descriptor names a
 *      built bundle as its entrypoint, so linking without building leaves the site importing
 *      a file that is not there.
 *   3. A plugin pinned to a different `emdash` than the site runs. The scaffold asked for
 *      0.x and installed 0.42.0 while the site ran 1.1.0 — so its passing test was evidence
 *      about a different CMS.
 *   4. `network:request` with nothing to allow. The bundle-time check rejects it, so failing
 *      here just fails earlier, with a better message.
 *
 * The manifest is parsed with regexes rather than a JSONC parser on purpose: this is a
 * lint, and `emdash-plugin validate` remains the authority on whether a manifest is valid.
 */
function audit() {
	const failures = [];

	const siteEmdash = readJson(`${SITE_DIR}/node_modules/emdash/package.json`)?.version ?? null;

	for (const dir of pluginDirs()) {
		const abs = `${PLUGINS_DIR}/${dir}`;
		const manifest = readJson(`${abs}/package.json`);
		if (!manifest) continue;

		const label = manifest.name ?? dir;
		const hasPluginManifest = existsSync(`${abs}/emdash-plugin.jsonc`);

		// 1. a script the toolchain cannot run.
		for (const [scriptName, command] of Object.entries(manifest.scripts ?? {})) {
			if (/\bemdash-plugin\b/.test(command) && !hasPluginManifest) {
				failures.push(
					`${label}: script "${scriptName}" runs emdash-plugin but the plugin has no emdash-plugin.jsonc — it can never succeed`,
				);
			}
		}

		// 2. the sandbox bundle has not been built.
		const entry = manifest.exports?.["./sandbox"];
		const relative = typeof entry === "string" ? entry : (entry?.import ?? entry?.default);
		if (hasPluginManifest && typeof relative === "string" && !existsSync(`${abs}/${relative}`)) {
			failures.push(
				`${label}: exports "./sandbox" → ${relative}, which does not exist — run \`mise run plugin:build\``,
			);
		}

		// 3. emdash drift from the site.
		const pinned = readJson(`${abs}/node_modules/emdash/package.json`)?.version ?? null;
		if (siteEmdash && pinned && pinned !== siteEmdash) {
			failures.push(
				`${label}: has emdash ${pinned} installed, but the site runs ${siteEmdash} — a green test here says nothing about the site`,
			);
		}

		// 4. network access declared with nothing to allow.
		if (hasPluginManifest) {
			const raw = readFileSync(`${abs}/emdash-plugin.jsonc`, "utf8");
			const list = (key) => new RegExp(`"${key}"\\s*:\\s*\\[([^\\]]*)\\]`).exec(raw)?.[1] ?? "";
			const capabilities = list("capabilities");
			if (
				capabilities.includes("network:request") &&
				!capabilities.includes("network:request:unrestricted")
			) {
				if (!list("allowedHosts").trim()) {
					failures.push(
						`${label}: declares network:request but allowedHosts is empty — the bundle-time check will reject it`,
					);
				}
			}
		}
	}

	if (failures.length) {
		console.error(`plugin:audit found ${failures.length} problem(s):`);
		for (const failure of failures) console.error(`  ✗ ${failure}`);
		process.exit(1);
	}
	console.log(`  ✓ ${pluginDirs().length} plugins consistent`);
}

switch (sub) {
	case "install":
		requireName();
		run("pnpm", ["install"], { cwd: `${PLUGINS_DIR}/${name}` });
		break;

	case "install-all":
		for (const dir of pluginDirs()) {
			console.log(`→ pnpm install in ${dir}`);
			run("pnpm", ["install"], { cwd: `${PLUGINS_DIR}/${dir}` });
		}
		break;

	case "link":
		// Plugins live in plugins/ but the site resolves them from its own node_modules;
		// symlinking keeps edits live.
		mkdirSync(`${SITE_DIR}/node_modules`, { recursive: true });
		for (const dir of pluginDirs()) {
			const pkg = JSON.parse(readFileSync(`${PLUGINS_DIR}/${dir}/package.json`, "utf8")).name;
			const target = `${SITE_DIR}/node_modules/${pkg}`;
			mkdirSync(dirname(target), { recursive: true });
			rmSync(target, { recursive: true, force: true });
			symlinkSync(`${PLUGINS_DIR}/${dir}`, target);
			console.log(`  ✓ linked ${pkg}`);
		}
		break;

	case "validate":
	case "bundle":
	case "build": {
		// The sandboxed-plugin flow (`@emdash-cms/plugin-cli`, binary `emdash-plugin`), which
		// needs an `emdash-plugin.jsonc`. Not every plugin is sandboxed, so this applies the
		// same rule as `typecheck`: run the plugin's own script. A plugin that declares it opts
		// in; one that does not is skipped rather than failed. Singular takes a name, plural
		// sweeps every plugin.
		//
		// `build` is separate from `bundle` on purpose: a sandboxed plugin's `./sandbox` export
		// points at the built bundle, so `plugin:link` without a build leaves the site
		// importing a file that does not exist yet.
		const targets = name ? [name] : pluginDirs();
		let ran = 0;
		for (const dir of targets) {
			const manifest = JSON.parse(readFileSync(`${PLUGINS_DIR}/${dir}/package.json`, "utf8"));
			if (!manifest.scripts?.[sub]) continue;
			console.log(`→ ${sub} ${manifest.name}`);
			run("pnpm", ["--dir", `${PLUGINS_DIR}/${dir}`, "run", sub]);
			ran += 1;
		}
		if (ran === 0) {
			console.error(`plugin:${sub}: no plugin declares a "${sub}" script — see docs/plugin.md`);
			process.exit(1);
		}
		break;
	}

	case "typecheck":
		// Every plugin that declares a `typecheck` script. Runs the plugin's own tsc, so the
		// plugin's tsconfig decides what is checked — not the site's.
		for (const dir of pluginDirs()) {
			const manifest = JSON.parse(readFileSync(`${PLUGINS_DIR}/${dir}/package.json`, "utf8"));
			if (!manifest.scripts?.typecheck) continue;
			console.log(`→ typecheck ${manifest.name}`);
			run("pnpm", ["--dir", `${PLUGINS_DIR}/${dir}`, "run", "typecheck"]);
		}
		break;

	case "audit":
		audit();
		break;

	case "catalog":
		await catalog(false);
		break;

	case "init": {
		// Scaffolds a NEW plugin, so it must run in plugins/ itself. The shared passthrough runs
		// in whichever plugin owns the CLI, which would nest the scaffold inside that plugin.
		const pluginName = process.argv[3];
		if (!pluginName) {
			console.error("plugin:init needs a name — e.g: mise run plugin:new -- my-plugin");
			process.exit(1);
		}
		run(PLUGIN_CLI, ["init", pluginName], { cwd: PLUGINS_DIR });
		break;
	}

	case "dev": {
		// The official watch loop. It must run IN the plugin being watched, not in whichever
		// plugin happens to own the CLI.
		const pluginName = process.argv[3];
		if (!pluginName) {
			console.error(
				"plugin:dev needs a plugin name — e.g: mise run plugin:dev -- plat-trunk-sandboxed",
			);
			process.exit(1);
		}
		const dir = `${PLUGINS_DIR}/${pluginName}`;
		if (!existsSync(dir)) {
			console.error(`no such plugin: ${pluginName}`);
			process.exit(1);
		}
		run("pnpm", ["--dir", dir, "exec", "emdash-plugin", "dev"]);
		break;
	}

	default:
		console.error(`plugins: unknown subcommand "${sub}"`);
		process.exit(1);
}
